app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class Quote:
    '''
    Quote class to define Quote Objects
    '''
    def __init__(self,quote,author):
        self.quote = quote
        self.author = author

class User(UserMixin,db.Model):
    __tablename__='users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index =True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    blogs = db.relationship('Blog', backref= 'user', lazy='dynamic')
    comments = db.relationship('Comment', backref='user', lazy='dynamic')

    def __repr__(self):
        return f'This user is {self.username}'
    
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

class PhotoProfile(db.Model):
    __tablename__ = 'profile_photos'

    id = db.Column(db.Integer,primary_key = True)
    pic_path = db.Column(db.String())
    user= db.Column(db.Integer,db.ForeignKey("users.id"))

class Blog(db.Model):
    __tablename__= 'blogs'

    id = db.Column(db.Integer, primary_key = True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    title = db.Column(db.String(255))
    blog = db.Column(db.String(), index= True)
    posted = db.Column(db.DateTime, default=datetime.utcnow())
    comments = db.relationship('Comment', backref='blog', lazy='dynamic')

    def save_blogs(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'Title: {self.title}'

class Comment(db.Model):
    __tablename__='comment'

    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String(255))
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    blog_id = db.Column(db.Integer, db.ForeignKey("blogs.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()
    
    @classmethod
    def get_comments(cls,id):
        comments = Comment.query.filter_by(blog_id=id).all()
        return comments

    def delete_comment(self):
        db.session.delete(self)
        db.session.commit()    

    def __repr__(self):
        return f'Comment: {self.comment}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import Required

class BlogForm(FlaskForm):
    title = StringField('Subject of Blog', validators=[Required()])
    blog = TextAreaField('Enter Your Opinion', validators=[Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    comment = TextAreaField('Comment',validators=[Required()])
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us something about you', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view ='auth.login'
photos = UploadSet('photos', IMAGES)
mail = Mail()

def create_app(config_name):

    app= Flask(__name__)

    app.config.from_object(config_options[config_name])
    config_options[config_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    from .request import configure_request
    configure_request(app)

    configure_uploads(app,photos)

    return app
    

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views

app/main/views.py
from flask import render_template,request,redirect,url_for,abort,flash
from ..models import User,PhotoProfile,Blog,Comment
from . import main
from ..request import get_quotes
from .. import db,photos
from .forms import BlogForm,CommentForm,UpdateProfile
from flask_login import login_required, current_user

@main.route('/')
def index():
    '''
    View root page that returns the index page and its data
    '''
    quote = get_quotes()
    
    title = 'MyBlog.com'

    return render_template('index.html', title=title, quote = quote)

@main.route('/new_blog', methods=['GET', 'POST'])
@login_required
def new_blog():
    form = BlogForm()
    if form.validate_on_submit():
        title = form.title.data
        blog = form.blog.data
        user_id = current_user
        new_blog = Blog(title=title, blog=blog, user_id=current_user._get_current_object().id)
        new_blog.save_blogs()

        return redirect(url_for('main.blogs'))
    return render_template('new_blog.html', form=form)

@main.route('/blogs', methods=['GET','POST'])
@login_required
def blogs():
    blogs = Blog.query.all()
    title = 'All Blogs'
    return render_template('all_blogs.html', title = title,blogs=blogs)

@main.route('/update_blog/<int:id>',methods = ['GET','POST'])
@login_required
def update_blog(id):
    blog = Blog.query.get(id)
    if blog.user.id != current_user.id:
        abort(403)

    form = BlogForm()

    if form.validate_on_submit():
        blog.title = form.title.data
        blog.blog = form.blog.data
        db.session.add(blog)
        db.session.commit()

        return redirect(url_for('main.blogs'))

    return render_template('update_blog.html',form =form)


@main.route('/delete_blog/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_blog(id):
    blog = Blog.query.get(id)
    if blog.user.id != current_user.id:
        abort(403)
    db.session.delete(blog)
    db.session.commit()
 
    return redirect(url_for('main.blogs'))


@main.route('/view_comments/<id>')
@login_required
def view_comments(id):
    comment = Comment.get_comments(id)
    title = 'View Comments'
    return render_template('comment.html', comment=comment, title=title)

@main.route('/comment/<int:blog_id>', methods=['GET','POST'])
@login_required
def comment(blog_id):
    form = CommentForm()
    blog = Blog.query.filter_by(id=blog_id).first()

    if form.validate_on_submit():
        comment = form.comment.data

        new_comment = Comment(comment=comment, user_id = current_user.id, blog_id=blog_id)
        new_comment.save_comment()
        return redirect(url_for('main.blogs'))
    return render_template('new_comment.html', form=form, blog_id=blog_id)

@main.route('/delete_comment/<int:comment_id>', methods=['GET', 'POST'])
@login_required
def delete_comment(comment_id):
    comment =Comment.query.get(comment_id)
    if comment.user.id != current_user.id:
        abort(403)
    db.session.delete(comment)
    db.session.commit()
   
    return redirect (url_for('main.blogs'))

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        user_photo = PhotoProfile(pic_path = path,user= user)
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/all_blogs.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{% block content %}
<div class="container">
    <h1 class="text-center" style="font-weight: bolder; text-decoration: underline;">VIEWING ALL
        BLOGS...</h1>
    <ul class="nav nav-pills nav-justified nav-fill" role="tablist">
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#allblogs" style="font-weight: bold;">All
                Blogs</a>
        </li>
    </ul>

    <div class="tab-content">
        <div class="container tab-pane fade" id="allblogs" class="border"><br>
            {{ macro.display(blogs)}}
        </div>

    </div>
</div>
{% endblock%}

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock%}

app/templates/comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-5">
            {% for comment in comment %}
            <ul>
                <li style="font-size: 20px; font-weight: bold;">Comment :{{comment.comment}}</li>
                <h5 style="font-weight: bold; font-size: 20px; text-decoration: underline; color: darkblue;">Posted
                    By:{{comment.user.username}}</h5>
                <a href="/delete_comment/{{comment.id}}" class="btn btn-danger">Delete Comment</a>
            </ul>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="jumbotron">
        <h2 class="text-center" style="font-weight: bolder; text-decoration: underline;">WELCOME TO MyBlog.com.</h2>
        <h2 class="text-center mt-2" style="font-weight: bold; text-decoration: underline;">Inspirational Quote:</h2>
        <h3 class="text-center">{{quote.quote}}</h3>
        <h3 class="text-center text-muted">--{{quote.author}}--</h3>
    </div>
</div>
{% endblock %}

app/templates/macros.html
{% macro display(blogs) %}
<div class="container">
    <div class="row">
        <div class="card">
            <div class="card-body col-md-8">
                {% if blogs %}
                {% for blog in blogs %}
                <h2 class="card-title">SUBJECT:{{blog.title}}</h2>
                <h3 class="card-subtitle mb-2">{{blog.blog}}</h3>
                <h4>POSTED BY:{{blog.user.username}}</h4>
                <h4 class="date text-muted">POSTED ON:{{blog.posted}}</h4>
                <a href="/comment/{{blog.id}}" class="btn btn-primary">Comment</a>
                <a href="/view_comments/{{blog.id}}" class="btn btn-primary">View Comments</a>
                <a href="/delete_blog/{{blog.id}}" class="btn btn-danger">Delete Blog</a>
                <a href="/update_blog/{{blog.id}}" class="btn btn-primary">Update Blog</a>

                {% endfor %}
                {%else%}
                <h4 class="text-center">NO BLOGS</h4>
                {% endif %}

            </div>
        </div>
    </div>
</div>
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> MyBlog.com </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="/new_blog">New Blog</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="/blogs">View Blogs</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">{{current_user.username}}</a></li>

                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
            </ul>

        </div>

    </div>
</div>

app/templates/new_blog.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8"></div>
        <div class="col-md-4">
            {{wtf.quick_form(form)}}
        </div>
    </div>
</div>
{% endblock %}

app/templates/new_comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div class="row">
        {% if all_comments %}
        <div class="col-md-4">
            {%for comment in all_comments%}
            <ul>
                <li style="font-weight: bold; font-size: 20px;">Comment:{{comment.comment}}</li>
                <h4>Posted By:--{{comment.user.username}}--</h4>
            </ul>
        </div>
        {% endfor %}
        <div class="col-md-5">
            {{wtf.quick_form(form)}}
        </div>
        {% else %}
        <div class="col-md-3">
            <p>No Comments Posted Yet</p>
        </div>
        <div class="col-md-5">
            {{wtf.quick_form(form)}}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">

        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>


            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio.</p>
            {% endif %}
        </div>


        <div class="col-md-4">

            {% if user.profile_pic_path %}

            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

            {%else%}
            <p>No profile picture</p>

            {% endif %}

            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post"
                enctype="multipart/form-data">

                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/update_blog.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">
    <div class="row">
        <h3>Update Blog</h3>
        <div class="col-md-8"></div>
        <div class="col-md-4">
            {{wtf.quick_form(form)}}
        </div>
    </div>
</div>
{% endblock %}